-- YumYard OS — live schema snapshot
-- Generated by direct introspection of the Supabase project (ebfiocmxdirsxtmgiudu)
-- on 2026-09-17, as a substitute for `supabase db pull` (Docker unavailable on
-- this machine). This is a reference snapshot, NOT a numbered migration file —
-- it documents the ACTUAL current shape of every table, constraint, index,
-- trigger, RLS policy, and function in the public schema, since local
-- migrations 0001-0007 had drifted significantly from what's actually live
-- (see 0009/0012 migration comments for details on that drift).
--
-- Do not apply this file as a migration — every object already exists live.
-- Use it to compare against 0001-0007, or as the base for writing an actual
-- baseline migration once Docker is available for `supabase db pull`.

-- ============================================================
-- EXTENSIONS
-- ============================================================
-- pgcrypto (gen_random_uuid, crypto, digest) lives in the `extensions` schema
-- and is referenced via search_path in every function below.

-- ============================================================
-- TABLES
-- ============================================================

create table public.tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.branches (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  slug text not null,
  address text,
  phone text,
  timezone text not null default 'Africa/Accra',
  currency_code text not null default 'GHS',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, slug)
);

create table public.workers (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  display_name text not null,
  username text not null,
  pin_hash text not null,
  role text not null default 'cashier'
    check (role in ('owner', 'admin', 'manager', 'supervisor', 'cashier')),
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, username)
);
create index workers_branch_username_idx on public.workers (branch_id, lower(username));

create table public.riders (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  display_name text not null,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.menu_categories (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  name text not null,
  slug text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, slug)
);

create table public.menu_items (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  category_id uuid references public.menu_categories(id) on delete set null,
  name text not null,
  slug text not null,
  description text,
  base_price numeric(12,2) not null check (base_price >= 0),
  image_url text,
  requires_protein boolean not null default false,
  is_available boolean not null default true,
  is_archived boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, slug)
);

create table public.menu_item_protein_options (
  id uuid primary key default gen_random_uuid(),
  menu_item_id uuid not null references public.menu_items(id) on delete cascade,
  name text not null check (name in ('Tilapia', 'Chicken')),
  price_adjustment numeric(12,2) not null default 0,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (menu_item_id, name)
);

create table public.shifts (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  worker_id uuid not null references public.workers(id) on delete restrict,
  status text not null default 'open'
    check (status in ('open', 'closing_review', 'closed')),
  opened_at timestamptz not null default now(),
  opening_confirmed_at timestamptz,
  closed_at timestamptz,
  opening_cash_expected numeric(12,2) not null default 0,
  opening_cash_actual numeric(12,2) not null default 0,
  opening_cash_variance numeric(12,2) not null default 0,
  opening_cash_source_shift_id uuid references public.shifts(id) on delete set null,
  cash_sales_total numeric(12,2) not null default 0,
  momo_sales_total numeric(12,2) not null default 0,
  hubtel_sales_total numeric(12,2) not null default 0,
  delivery_fee_total numeric(12,2) not null default 0,
  cash_paid_in_total numeric(12,2) not null default 0,
  cash_paid_out_total numeric(12,2) not null default 0,
  cash_refund_total numeric(12,2) not null default 0,
  expected_cash numeric(12,2),
  actual_cash_counted numeric(12,2),
  cash_variance numeric(12,2),
  open_order_count_at_close integer not null default 0,
  handover_order_count integer not null default 0,
  closing_note text,
  requires_admin_approval boolean not null default false,
  approved_by_worker_id uuid references public.workers(id) on delete set null,
  approved_at timestamptz,
  closed_by_session_id uuid references public.worker_sessions(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index shifts_branch_worker_status_idx on public.shifts (branch_id, worker_id, status);
create unique index shifts_one_open_shift_per_branch_idx on public.shifts (branch_id)
  where (status in ('open', 'closing_review'));

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  order_number text not null,
  status text not null default 'confirmed'
    check (status in ('draft', 'confirmed', 'preparing', 'ready', 'awaiting_pickup',
                       'out_for_delivery', 'completed', 'cancelled', 'voided')),
  fulfillment_type text not null
    check (fulfillment_type in ('walk-in', 'pickup', 'delivery', 'dine-in')),
  source text not null default 'direct-pos'
    check (source in ('direct-pos', 'phone-call', 'whatsapp', 'hubtel', 'other')),
  customer_name text,
  customer_phone text,
  delivery_address text,
  delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0),
  rider_id uuid references public.riders(id) on delete set null,
  order_notes text,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  created_by_worker_id uuid not null references public.workers(id) on delete restrict,
  created_in_shift_id uuid not null references public.shifts(id) on delete restrict,
  completed_by_worker_id uuid references public.workers(id) on delete set null,
  completed_in_shift_id uuid references public.shifts(id) on delete set null,
  completed_at timestamptz,
  handed_over_from_shift_id uuid references public.shifts(id) on delete set null,
  handed_over_to_shift_id uuid references public.shifts(id) on delete set null,
  handed_over_at timestamptz,
  handover_note text,
  cancelled_by_worker_id uuid references public.workers(id) on delete set null,
  cancelled_at timestamptz,
  cancellation_reason text,
  last_updated_by_worker_id uuid references public.workers(id) on delete set null,
  last_updated_in_shift_id uuid references public.shifts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, order_number)
);
create index orders_branch_created_at_idx on public.orders (branch_id, created_at desc);
create index orders_shift_idx on public.orders (created_in_shift_id);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  item_name text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  protein_choice text check (protein_choice in ('Tilapia', 'Chicken')),
  line_total numeric(12,2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete restrict,
  payment_method text not null check (payment_method in ('cash', 'momo', 'hubtel')),
  amount numeric(12,2) not null check (amount > 0),
  reference text,
  received_by_worker_id uuid not null references public.workers(id) on delete restrict,
  received_in_shift_id uuid not null references public.shifts(id) on delete restrict,
  received_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index payments_shift_idx on public.payments (received_in_shift_id);

create table public.cash_movements (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  shift_id uuid not null references public.shifts(id) on delete restrict,
  recorded_by_worker_id uuid not null references public.workers(id) on delete restrict,
  movement_type text not null check (movement_type in ('paid_in', 'paid_out', 'refund')),
  amount numeric(12,2) not null check (amount > 0),
  reason text not null,
  created_at timestamptz not null default now()
);

create table public.worker_sessions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  worker_id uuid not null references public.workers(id) on delete cascade,
  access_area text not null check (access_area in ('pos', 'admin')),
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12:00:00'),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  revoked_reason text,
  ip_hint text,
  user_agent_hint text
);
create index worker_sessions_active_lookup_idx on public.worker_sessions (token_hash)
  where (revoked_at is null);
create index worker_sessions_worker_active_idx on public.worker_sessions (worker_id, expires_at desc)
  where (revoked_at is null);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  branch_id uuid references public.branches(id) on delete cascade,
  worker_id uuid references public.workers(id) on delete set null,
  shift_id uuid references public.shifts(id) on delete set null,
  entity_type text not null,
  entity_id uuid,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
-- RLS is enabled on ALL 14 tables. Only the three public menu-browsing
-- tables have policies (deliberate public read for the customer-facing
-- menu, scoped to available/active rows). Every other table has RLS
-- enabled with NO policies, which is a deliberate deny-all: combined
-- with the grant revocations in 0009/0012, the only way in is through
-- the SECURITY DEFINER RPC functions below.

alter table public.tenants enable row level security;
alter table public.branches enable row level security;
alter table public.workers enable row level security;
alter table public.riders enable row level security;
alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.menu_item_protein_options enable row level security;
alter table public.shifts enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.cash_movements enable row level security;
alter table public.worker_sessions enable row level security;
alter table public.audit_logs enable row level security;

create policy "Allow public read of active menu categories"
  on public.menu_categories for select
  using (is_active = true);

create policy "Allow public read of available menu items"
  on public.menu_items for select
  using (is_available = true and is_archived = false);

create policy "Allow public read of protein options"
  on public.menu_item_protein_options for select
  using (true);

-- ============================================================
-- TRIGGERS
-- ============================================================

create trigger tenants_set_updated_at before update on public.tenants
  for each row execute function public.set_updated_at();
create trigger branches_set_updated_at before update on public.branches
  for each row execute function public.set_updated_at();
create trigger workers_set_updated_at before update on public.workers
  for each row execute function public.set_updated_at();
create trigger riders_set_updated_at before update on public.riders
  for each row execute function public.set_updated_at();
create trigger menu_categories_set_updated_at before update on public.menu_categories
  for each row execute function public.set_updated_at();
create trigger menu_items_set_updated_at before update on public.menu_items
  for each row execute function public.set_updated_at();
create trigger shifts_set_updated_at before update on public.shifts
  for each row execute function public.set_updated_at();
create trigger orders_set_updated_at before update on public.orders
  for each row execute function public.set_updated_at();

-- ============================================================
-- FUNCTIONS
-- ============================================================
-- Full bodies for all 19 functions live in migrations 0008-0012 (the ones
-- this Backend/DB Engineer role touched) plus the original 0001-0007 files
-- (authenticate_worker, current_worker_session, hash_session_token,
-- lock_worker_session, open_worker_shift, get_active_worker_shift,
-- get_shift_opening_context, create_pos_order, record_order_payment,
-- handover_open_order, claim_handover_orders_for_shift,
-- get_pending_handover_orders). Not re-listed here in full to avoid this
-- snapshot drifting out of sync with the numbered migrations that are the
-- actual source of truth for function bodies going forward.
--
-- Full current list (19): authenticate_worker, claim_handover_orders_for_shift,
-- close_worker_shift, create_pos_order, current_worker_session,
-- get_active_worker_shift, get_order_payment_summary,
-- get_pending_handover_orders, get_pos_active_orders,
-- get_pos_session_and_shift, get_shift_close_preview,
-- get_shift_opening_context, handover_open_order, hash_session_token,
-- lock_worker_session, open_worker_shift, record_order_payment,
-- set_updated_at, update_pos_order_status.

-- ============================================================
-- GRANTS
-- ============================================================
-- All direct table access for anon/authenticated is revoked except
-- SELECT on menu_categories/menu_items/menu_item_protein_options
-- (see migration 0009). All 19 functions above are granted EXECUTE to
-- anon and authenticated - this is intentional, they are the only
-- sanctioned entry point into the system (see migration 0012 for the
-- full reasoning).
